"""add transaction account id

Revision ID: 05c44e034527
Revises: c68b86e03063
Create Date: 2025-01-26 00:02:59.151447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05c44e034527'
down_revision = 'c68b86e03063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_transactions_account_id_accounts'), 'accounts', ['account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transactions_account_id_accounts'), type_='foreignkey')
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###
