"""Rename transaction type

Revision ID: 0a7579857a13
Revises: 5df866166687
Create Date: 2025-01-31 16:31:18.662391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a7579857a13'
down_revision = '5df866166687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_type', sa.String(), nullable=True))
        batch_op.drop_column('transactionType')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transactionType', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('transaction_type')

    # ### end Alembic commands ###
