"""remove account_type from user

Revision ID: 1c09cd8a0160
Revises: ca6b27574157
Create Date: 2025-01-21 13:53:22.224986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c09cd8a0160'
down_revision = 'ca6b27574157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('account_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_type', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
