"""fix transactions account key

Revision ID: 8a6b04b82310
Revises: 05c44e034527
Create Date: 2025-01-26 00:04:24.276541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a6b04b82310'
down_revision = '05c44e034527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_accounts_transaction_id_transactions', type_='foreignkey')
        batch_op.drop_column('transaction_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_accounts_transaction_id_transactions', 'transactions', ['transaction_id'], ['id'])

    # ### end Alembic commands ###
