"""add account type column

Revision ID: ca6b27574157
Revises: 7f1c609f7a54
Create Date: 2025-01-20 20:42:35.423528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca6b27574157'
down_revision = '7f1c609f7a54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_type', sa.String(), nullable=True))
        batch_op.drop_column('transaction_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_count', sa.INTEGER(), nullable=True))
        batch_op.drop_column('account_type')

    # ### end Alembic commands ###
